### ISSUE TITLE
Problems with PAR

### ISSUE THREAD

**Issue by gwyn17** [briandfoy/business-isbn-data#6]
Business::ISBN::Data doesn't work out of the box with PAR.  This is not surprising.
The error message is not helpful.
```
Could not open  to get ISBN range data [No such file or directory]
 at Business/ISBN.pm line 87.
```
The solution has 2 steps.
* Add the following to your pp invocation.
```
-a 'YOUR PATH/lib/perl5/Business/ISBN/RangeMessage.xml;lib/Business/ISBN/RangeMessage.xml'
```

* Add the following before Business::ISBN is invoked.
```perl
BEGIN {
    if( $ENV{PAR_TEMP} ) {
        $ENV{ISBN_RANGE_MESSAGE} = File::Spec->catfile( $ENV{PAR_TEMP}, qw( inc lib Business ISBN RangeMessage.xml ) );
    }
}
```

This could be added to the doco.  Or just let google find this issue to help future generations.

**Comment by briandfoy** [comment]
I think there's a better approach. The module should be able to survive a missing _RangeMessage.xml_ file since the same data are in the module. The  _RangeMessage.xml_ is there so you can use one that's newer than what the module provides.

What's actually happening is that it tests a bunch of potential file paths and then tries the one it finds. However, in this case, it finds nothing, so instead of realizing it has the empty list, it tries no value. That's why the error message is a bit weird. It was expecting a filename but got undef. 

So, even though you got the warning, the code should have worked because it picked up the default data. Was there something past the warning that did not work?

**Comment by briandfoy** [comment]
Try 20210112.002, on its way to CPAN.

**Comment by gwyn17** [comment]
I will admit I didn't test if it still worked.  I saw the warning message, debugged and fixed the problem.

Also, I think a note in the doco about how to get the XML to work with PAR is a good thing.

**Comment by briandfoy** [comment]
Well, you don't need the XML file. There's no point to packaging it because it's the same data you get from the module. It's there if you want to drop in a newer version.

**Comment by gwyn17** [comment]
Fair enough.

**Comment by gwyn17** [comment]
Also - I should be working on the project that uses Business::Barcode::Data this afternoon and will port success.

**Comment by gwyn17** [comment]
I can confirm that the warning message no longer appears when packed into a PAR without RangeMassage.xml.

However, without RangeMessage.xml, the ISBN-13 9782021183061 is invalid.  With RangeMessage.xml, that ISBN is valid.  I don't know if this is expected result.

**Comment by briandfoy** [comment]
Let's move this to a new issue because it's an unrelated problem. And, since this issue is closed, continuing discussion doesn't show up in my "open issue" list.

**Comment by gwyn17** [comment]
I can confirm that Business::ISBN 3.006 and Business::ISBN::Data 20210112.005 are behaving as expected.  Thank you.
